const receivedData = [
  {
    movie_id: "tt2488496",
    image: "https://m.media-amazon.com/images/M/MV5BOTAzODEzNDAzMl5BMl5BanBnXkFtZTgwMDU1MTgzNzE@._V1_Ratio0.6837_AL_.jpg",
    title: "Star Wars: Episode VII - The Force Awakens",
    year_released: "(2015)",
    runtime: "138 min",
    genres: "Action, Adventure, Sci-Fi",
    content_rating: "PG-13",
    imDb_rating: "7.8",
    metacritic_rating: "80",
    summery: "As a new threat to the galaxy rises, Rey, a desert scavenger, and Finn, an ex-stormtrooper, must join Han Solo and Chewbacca to search for the one hope of restoring peace.",
    cast: "J.J. Abrams, Daisy Ridley, John Boyega, Oscar Isaac, Domhnall Gleeson"
  },
  {
    movie_id: "tt4154796",
    image: "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_Ratio0.6837_AL_.jpg",
    title: "Avengers: Endgame",
    year_released: "(2019)",
    runtime: "181 min",
    genres: "Action, Adventure, Drama",
    content_rating: "PG-13",
    imDb_rating: "8.4",
    metacritic_rating: "78",
    summery: "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    cast: "Anthony Russo, Joe Russo, Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth"
  },
  {
    movie_id: "tt10872600",
    image: "https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_Ratio0.6837_AL_.jpg",
    title: "Spider-Man: No Way Home",
    year_released: "(2021)",
    runtime: "148 min",
    genres: "Action, Adventure, Fantasy",
    content_rating: "PG-13",
    imDb_rating: "8.3",
    metacritic_rating: "71",
    summery: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    cast: "Jon Watts, Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon"
  },
  {
    movie_id: "tt0499549",
    image: "https://m.media-amazon.com/images/M/MV5BZDA0OGQxNTItMDZkMC00N2UyLTg3MzMtYTJmNjg3Nzk5MzRiXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_Ratio0.6837_AL_.jpg",
    title: "Avatar",
    year_released: "(2009)",
    runtime: "162 min",
    genres: "Action, Adventure, Fantasy",
    content_rating: "PG-13",
    imDb_rating: "7.8",
    metacritic_rating: "83",
    summery: "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
    cast: "James Cameron, Sam Worthington, Zoe Saldana, Sigourney Weaver, Michelle Rodriguez"
  },
  {
    movie_id: "tt2488496",
    image: "https://m.media-amazon.com/images/M/MV5BOTAzODEzNDAzMl5BMl5BanBnXkFtZTgwMDU1MTgzNzE@._V1_Ratio0.6837_AL_.jpg",
    title: "Star Wars: Episode VII - The Force Awakens",
    year_released: "(2015)",
    runtime: "138 min",
    genres: "Action, Adventure, Sci-Fi",
    content_rating: "PG-13",
    imDb_rating: "7.8",
    metacritic_rating: "80",
    summery: "As a new threat to the galaxy rises, Rey, a desert scavenger, and Finn, an ex-stormtrooper, must join Han Solo and Chewbacca to search for the one hope of restoring peace.",
    cast: "J.J. Abrams, Daisy Ridley, John Boyega, Oscar Isaac, Domhnall Gleeson"
  },
  {
    movie_id: "tt4154796",
    image: "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_Ratio0.6837_AL_.jpg",
    title: "Avengers: Endgame",
    year_released: "(2019)",
    runtime: "181 min",
    genres: "Action, Adventure, Drama",
    content_rating: "PG-13",
    imDb_rating: "8.4",
    metacritic_rating: "78",
    summery: "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    cast: "Anthony Russo, Joe Russo, Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth"
  },
  {
    movie_id: "tt10872600",
    image: "https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_Ratio0.6837_AL_.jpg",
    title: "Spider-Man: No Way Home",
    year_released: "(2021)",
    runtime: "148 min",
    genres: "Action, Adventure, Fantasy",
    content_rating: "PG-13",
    imDb_rating: "8.3",
    metacritic_rating: "71",
    summery: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    cast: "Jon Watts, Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon"
  },
  {
    movie_id: "tt0499549",
    image: "https://m.media-amazon.com/images/M/MV5BZDA0OGQxNTItMDZkMC00N2UyLTg3MzMtYTJmNjg3Nzk5MzRiXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_Ratio0.6837_AL_.jpg",
    title: "Avatar",
    year_released: "(2009)",
    runtime: "162 min",
    genres: "Action, Adventure, Fantasy",
    content_rating: "PG-13",
    imDb_rating: "7.8",
    metacritic_rating: "83",
    summery: "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
    cast: "James Cameron, Sam Worthington, Zoe Saldana, Sigourney Weaver, Michelle Rodriguez"
  },
  {
    movie_id: "tt2488496",
    image: "https://m.media-amazon.com/images/M/MV5BOTAzODEzNDAzMl5BMl5BanBnXkFtZTgwMDU1MTgzNzE@._V1_Ratio0.6837_AL_.jpg",
    title: "Star Wars: Episode VII - The Force Awakens",
    year_released: "(2015)",
    runtime: "138 min",
    genres: "Action, Adventure, Sci-Fi",
    content_rating: "PG-13",
    imDb_rating: "7.8",
    metacritic_rating: "80",
    summery: "As a new threat to the galaxy rises, Rey, a desert scavenger, and Finn, an ex-stormtrooper, must join Han Solo and Chewbacca to search for the one hope of restoring peace.",
    cast: "J.J. Abrams, Daisy Ridley, John Boyega, Oscar Isaac, Domhnall Gleeson"
  },
  {
    movie_id: "tt4154796",
    image: "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_Ratio0.6837_AL_.jpg",
    title: "Avengers: Endgame",
    year_released: "(2019)",
    runtime: "181 min",
    genres: "Action, Adventure, Drama",
    content_rating: "PG-13",
    imDb_rating: "8.4",
    metacritic_rating: "78",
    summery: "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    cast: "Anthony Russo, Joe Russo, Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth"
  },
  {
    movie_id: "tt10872600",
    image: "https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_Ratio0.6837_AL_.jpg",
    title: "Spider-Man: No Way Home",
    year_released: "(2021)",
    runtime: "148 min",
    genres: "Action, Adventure, Fantasy",
    content_rating: "PG-13",
    imDb_rating: "8.3",
    metacritic_rating: "71",
    summery: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    cast: "Jon Watts, Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon"
  },
  {
    movie_id: "tt0499549",
    image: "https://m.media-amazon.com/images/M/MV5BZDA0OGQxNTItMDZkMC00N2UyLTg3MzMtYTJmNjg3Nzk5MzRiXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_Ratio0.6837_AL_.jpg",
    title: "Avatar",
    year_released: "(2009)",
    runtime: "162 min",
    genres: "Action, Adventure, Fantasy",
    content_rating: "PG-13",
    imDb_rating: "7.8",
    metacritic_rating: "83",
    summery: "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
    cast: "James Cameron, Sam Worthington, Zoe Saldana, Sigourney Weaver, Michelle Rodriguez"
  },
  {
    movie_id: "tt2488496",
    image: "https://m.media-amazon.com/images/M/MV5BOTAzODEzNDAzMl5BMl5BanBnXkFtZTgwMDU1MTgzNzE@._V1_Ratio0.6837_AL_.jpg",
    title: "Star Wars: Episode VII - The Force Awakens",
    year_released: "(2015)",
    runtime: "138 min",
    genres: "Action, Adventure, Sci-Fi",
    content_rating: "PG-13",
    imDb_rating: "7.8",
    metacritic_rating: "80",
    summery: "As a new threat to the galaxy rises, Rey, a desert scavenger, and Finn, an ex-stormtrooper, must join Han Solo and Chewbacca to search for the one hope of restoring peace.",
    cast: "J.J. Abrams, Daisy Ridley, John Boyega, Oscar Isaac, Domhnall Gleeson"
  },
  {
    movie_id: "tt4154796",
    image: "https://m.media-amazon.com/images/M/MV5BMTc5MDE2ODcwNV5BMl5BanBnXkFtZTgwMzI2NzQ2NzM@._V1_Ratio0.6837_AL_.jpg",
    title: "Avengers: Endgame",
    year_released: "(2019)",
    runtime: "181 min",
    genres: "Action, Adventure, Drama",
    content_rating: "PG-13",
    imDb_rating: "8.4",
    metacritic_rating: "78",
    summery: "After the devastating events of Avengers: Infinity War (2018), the universe is in ruins. With the help of remaining allies, the Avengers assemble once more in order to reverse Thanos' actions and restore balance to the universe.",
    cast: "Anthony Russo, Joe Russo, Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth"
  },
  {
    movie_id: "tt10872600",
    image: "https://m.media-amazon.com/images/M/MV5BZWMyYzFjYTYtNTRjYi00OGExLWE2YzgtOGRmYjAxZTU3NzBiXkEyXkFqcGdeQXVyMzQ0MzA0NTM@._V1_Ratio0.6837_AL_.jpg",
    title: "Spider-Man: No Way Home",
    year_released: "(2021)",
    runtime: "148 min",
    genres: "Action, Adventure, Fantasy",
    content_rating: "PG-13",
    imDb_rating: "8.3",
    metacritic_rating: "71",
    summery: "With Spider-Man's identity now revealed, Peter asks Doctor Strange for help. When a spell goes wrong, dangerous foes from other worlds start to appear, forcing Peter to discover what it truly means to be Spider-Man.",
    cast: "Jon Watts, Tom Holland, Zendaya, Benedict Cumberbatch, Jacob Batalon"
  },
  {
    movie_id: "tt0499549",
    image: "https://m.media-amazon.com/images/M/MV5BZDA0OGQxNTItMDZkMC00N2UyLTg3MzMtYTJmNjg3Nzk5MzRiXkEyXkFqcGdeQXVyMjUzOTY1NTc@._V1_Ratio0.6837_AL_.jpg",
    title: "Avatar",
    year_released: "(2009)",
    runtime: "162 min",
    genres: "Action, Adventure, Fantasy",
    content_rating: "PG-13",
    imDb_rating: "7.8",
    metacritic_rating: "83",
    summery: "A paraplegic Marine dispatched to the moon Pandora on a unique mission becomes torn between following his orders and protecting the world he feels is his home.",
    cast: "James Cameron, Sam Worthington, Zoe Saldana, Sigourney Weaver, Michelle Rodriguez"
  },
]

module.exports = receivedData;